When dumping the database, close the outputstream once the dump is done
vorburger/MariaDB4j pull request #502
Opened 2021-11-30 15:06 UTC by robin-xyzt-ai

This should fix #340 .

The created outputstream is now closed using a process listenere, which should get triggered when the dump is either done or has failed.

Alas, no test in this commit.

- I couldn't find any existing tests that perform a dump
- Even if there would be such a test, I would not know how to check from Java code whether that file stream is closed, unless I added some ugly code to grant me access to that stream

If you really want to have a test for this, some pointers in how you would approach testing this are welcome

2021-11-30 17:06 UTC, vorburger requested changes

2021-11-30 17:06 UTC, vorburger commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
> +                    outputStream.close();
@robin-xyzt-ai first of all a big Thank You for stepping up to fix this issue!

But I'm not sure the fix as-is is entirely correct. This line will close the `BufferedOutputStream`, and as far as I know that would not automagically also close that `FileOutputStream` created in line 485? Do you see what I mean and agree to amend this close both of them, or am I wrong and confused?

2021-11-30 17:09 UTC, vorburger commented
I'm OK to merge this PR for that particular bug without test coverage. The effort to create one far outweighs the benefit in this case, I agree. If you really had and wanted to, you would have to somehow intercept / mock the FS impl... something like https://github.com/google/jimfs comes to mind, but I'm not even sure that has any way to "check if the virtual (in-memory) file has been closed" - probably not. Another route, more fruitful, would probably be to use some platform speicific native library, or even `exec` (LOL, the irony, as a test in a library that is itself an exec wrapper) out to some `lsof` type external binary, to check if the dump file is still open. Long story short - forget about it.

2021-11-30 18:36 UTC, vorburger commented
> I couldn't find any existing tests that perform a dump

just FYI there IS a https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleDumpTest.java (note that most of the "interesting" tests are in the mariaDB4j module, not the mariaDB4j-core module where the code is)

2021-11-30 19:54 UTC, vorburger commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
> +                    outputStream.close();
It seems I'm wrong about this... `BufferedOutputStream`, in it's parent `FilterOutputStream.close()` actually does `out.close();` and its JavaDoc explicitly says _"...  pass all requests to the underlying output stream"._

2021-11-30 19:55 UTC, vorburger approved these changes

2021-11-30 19:55 UTC, merged

2021-12-01 07:45 UTC, robin-xyzt-ai commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
> +                    outputStream.close();
Indeed. As such, it's not an implementation detail but documented behavior. As such, we could rely on it