Initial working pass of MariaDB 10.6.12...
vorburger/MariaDB4j pull request #710
Opened 2023-03-28 16:08 UTC by TheKnowles

Initial working pass of MariaDB 10.6.12 for linux with a simulated start for winx64. OSX support is currently not available.  

Opening this PR knowing it cannot currently be merged to main. I am looking for additional eyes on this and suggestions.

Originally, I branched off of the last commit prior to the upgrade to Java 17. 

After I attempted to use it in my software (Java 11, Spring 5 / Boot 2.7.x), I ran into an issue where the annotations had been switched from javax to jakarta as part of the move to Spring 6. I then moved my branch to right before this change.

I would like to suggest creating a 2.x release branch that maintains a Java 11 / Spring 5 release and allow 3.x + to be Java 17 onwards. But this becomes a nightmare quickly because more recent MariaDB instances are not necessarily tied to the user's Java version, nor what version of Spring they are using. Fixes to MariaDB4j itself would then need to get backpatched to prior release branches as applicable.

The compatibility matrix effectively becomes MariaDB / Spring Framework / this product.

I don't mind doing the work for this, but at what point do we want cutoff retrofitting here versus maintaining a hard fork? Open to suggestions.

Having that said, this update was quite bespoke. In no particular order, several challenges that had to be solved to get 10.6.12 working in Linux:

1. MariaDB changed their download urls since the 10.3 commit to this repository.
2. MariaDB 10.4 removed no password root user. Additional commentary below
3. MariaDB 10.5.2 onward swapped how they did sym links between mysql* and maria* equivalents. Additional commentary below
4. OSX support was incomprehensible.
5. Consolidated slf4j to version 2.0.6. 1.7.x and 2.x results in NOOP binding

**DL URL**

https://dlm.mariadb.com/browse/mariadb_server/ ... versus the previous url in 10.3

Looks like Win32 support was dropped at some point.

**Root user:**

https://mariadb.com/kb/en/authentication-from-mariadb-104/

You can use the user that owns the data directory (generally the user that started MariaDB4j) to give the root user a password to continue the functionality of the unit tests.

**Sym links:**

I updated the entire codebase to reference maria* instead of mysql for binaries.

**OSX:**

Bintray was decommisioned in May 2021. Homebrew OCI got moved to Github Content Repository which is a Docker repo. After a lot of hunting and trying to figure out how to at least simulate a download, I got stuck at pulling the OCI from GHCR here: 

https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fmariadb%2F10.6/69479903?tag=10.6.12

Because I was not on the right OS, docker would not pull. 

I believe people have ran into this before and effectively have to build from source themselves or be on osx.

2023-03-28 16:56 UTC, TheKnowles commented
Related: https://github.com/vorburger/MariaDB4j/issues/344 https://github.com/vorburger/MariaDB4j/issues/699

2023-04-17 17:26 UTC, vorburger commented on DBs/pom.xml
> +<!--        <module>mariaDB4j-db-win32-10.6.12</module>-->
Why is this commented? You can (should) uncomment this, so that it can be tested by others - and eventually deployed.

2023-04-17 17:27 UTC, vorburger commented on DBs/pom.xml
> +	    <module>mariaDB4j-db-mac64-10.2.11</module>
Clean this up and revert this effectively formatting only change here, to avoid confusion?

2023-04-17 17:27 UTC, vorburger commented on DBs/pom.xml
> +<!--        <module>mariaDB4j-db-linux64-10.6.12</module>-->
Uncomment this (as above for the Windows version).

2023-04-17 17:28 UTC, vorburger commented on README.md
> +    <version>2.7.0</version>
Nope, please revert this? 😄

2023-04-17 17:29 UTC, vorburger commented on README.md
> +    <version>2.7.0-SNAPSHOT</version>
revert please, as above

2023-04-17 17:29 UTC, vorburger commented on mariaDB4j-app/pom.xml
> +		<version>2.7.0-SNAPSHOT</version>
nope, please revert

2023-04-17 17:29 UTC, vorburger commented on mariaDB4j-core/pom.xml
> +        <version>2.7.0-SNAPSHOT</version>
nope, please revert

2023-04-17 17:40 UTC, vorburger commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
> +        builder.setOutputStreamLogDispatcher(getOutputStreamLogDispatcher("mariadb-install-db"));
May I ask why?

2023-04-17 17:45 UTC, vorburger commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
> +        executables.putIfAbsent(Dump, () -> new File(baseDir, "bin/mariadb-dump" + getExtension()));
Oh, so the binaries all have new names in recent MariaDB versions? Interesting. But that then means that after merging this it will ONLY work with those new binaries. I'm torn about this, because the idea was that one could just put another binaries JAR on the classpath and it would still work. Hm... perhaps should be made configurable, then? Are you willing to work on this PR to introduce that? Or perhaps first raise a simpler separate PR proposing that?

2023-04-17 17:45 UTC, vorburger commented on mariaDB4j-maven-plugin/pom.xml
> +        <version>2.7.0-SNAPSHOT</version>
revert please, as above

2023-04-17 17:45 UTC, vorburger commented on mariaDB4j-springboot/pom.xml
> +        <version>2.7.0-SNAPSHOT</version>
revert please, as above

2023-04-17 17:45 UTC, vorburger commented on mariaDB4j/pom.xml
> +		<version>2.7.0-SNAPSHOT</version>
revert please, as above

2023-04-17 17:46 UTC, vorburger commented on mariaDB4j/src/test/java/ch/vorburger/mariadb4j/StartSimulatedForAllPlatformsTest.java
> +//    }
Agreed, but isn't this actually unrelated to the purpose of this PR, to bump for Linux & Windows? Or do you "need" this, here?

2023-04-17 17:46 UTC, TheKnowles commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
> +        builder.setOutputStreamLogDispatcher(getOutputStreamLogDispatcher("mariadbd"));
Starting with mariadb 10.5.2 the bootstrap script is mariadb-install-db.
Sym linking the older script mysql_install_db caused the unpacked jar to not have the correct platform sub directory.

2023-04-17 17:47 UTC, TheKnowles commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java
> +        builder.setOutputStreamLogDispatcher(getOutputStreamLogDispatcher("mariadb-install-db"));
Starting with mariadb 10.5.2 the bootstrap script is mariadb-install-db.
Sym linking the older script mysql_install_db caused the unpacked jar to not have the correct platform sub directory.

2023-04-17 17:49 UTC, vorburger commented on mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
> -        if (!dbName.equals("test")) {
Why this change? Do newer versions of MariaDB not "already have a DB named "test"? Then the inline comment below shouldn't be kept... This is actually kind of related to the other discussion, above; it will break anyone wanting to use older JARs. How about making this conditional of the MariaDB version?

2023-04-17 17:50 UTC, vorburger commented on mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
> +            conn = DriverManager.getConnection(db.getConfiguration().getURL(dbName), System.getProperty("user.name"), "");
This is interesting. I guess it's... cleaner? Would you be willing to submit a small PR just for this?

2023-04-17 17:53 UTC, vorburger commented on mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
> +        db.run("SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');", System.getProperty("user.name"), "");
Oh, interesting. Because this test is also the "Tutorial", in a sense this promotes doing something "insecure". I'm actually a bit confused why the root user is still required if `System.getProperty("user.name")` is being use above. I wonder if there is a better solution for this. Could this entire TutorialTest just not use the (DB, not OS) `root` user at all? Perhaps improving this is worth a separate smaller PR, as a pre-requisite for this?

2023-04-17 17:53 UTC, vorburger commented on pom.xml
> +	<version>2.7.0-SNAPSHOT</version>
revert please, as above

2023-04-17 17:57 UTC, vorburger requested changes
@TheKnowles Thank You for this!!! My apologies for the 3 week delay in reviewing. Unfortunately I can only work on this project occassionally. I'm hoping that my review feedback here is "motivating" to sort this out together to get it to a state where it can be merged, and not ... "harsh" in any way? I really do appreciate the contribution, but this PR will require some work. Also it needs to be rebased on the current `main` branch, as per related inline comment, and #717.

2023-04-20 17:31 UTC, closed without merging